sudo: required
services:
- docker
language: node_js
node_js:
- '8'
script:
- npm test
after_success:
- sh .travis/push_dockerhub.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=clients
  - HEROKU_APP_NAME=iosr2017-clients
  - secure: yDWpRcr3C8ycIPTh6wK915cj4IZ8b8dd1fKvgEO4ZLcwPSnov/j6XjOUNhnro39WlzLxd8j3RNpKSS1UNUE7Zlje8dqeWy4iIN6unflmzD3owobzxOneas+KLCMZOcVY2ajpF3RvygsEt+uWpJJ8pw3fP36GAy1pPSDFOzkxrZAQogZfSfKkqljuodkNybtVfGonEkzdUGBrS0YprcOXrPXSAOZBkK+g6RWGmh9M7RBkqh8aD3xHE1vd743aD9YUdFORyjlBJMJDKdgO+ILoSd9OhNZc2FIif3JNMjiQwrDNY3BxNigvNenF6p1sNCPBio+D2G9Mkt6184XmgaTouWylp5Mc/CGsHs6MnAAAvUJlT4CxU/OdWAA+oJIWQrjXq2WDAxJXGg282gabaZ9mrFe0JBOQQeIaukgiqio8cvrhcaIJV7MV5M/e1PclYIrb1qwmurppHUu9Rk3AgQJvXqImUvm2Ef2VG+2f7TGsAk47+nJsHPoMm4V2mAM/wU8PbT3VDvps0DKyBIKME5hn7+FoDFyP5YlbvTFIwiTpSzrCcCrOtjKJfrn8chzqwZcF/2267vwXvjztFSpVrR2H1is/AEsRIte2dPTUAaZAB1uchox+CP3wBKQwdj6sycA+YbvNNE10HO1fTkHwABaSdhKWtvkc8/ywRifIPim8qeY=
  - secure: GUrZnGXfT+EGaFlyoiuQJEq3piBLIoVXIqUXDf6yFJw/fdW4M0TXWsujOt9GiaWqiiP7716xZl1C1jdrYsGBZAL33NdLik/pqY5jnLL5iE5ZqHSg6xxM5d8Wmi0LRzdbRIG7KN6WEa2+WpcSBJDWozzE0+rn69Ffooh8fNXvAGPxphL1Im7NXAaOHMUPCSivL7/fRdn7M8KQDTx4VVGFc2/kI1Ih4Kvc2ODEATd79MKcKUPFBh7qlHKI2D1GNu1Ij6OwswAfb6lKqnztCfEofNzvBdMVckYQnCM3Aaqjm+CkPZJMb09PN6tChYvCstjCsXaMG/EeNlfnBmsdXzFduQty1iS9vIWu6VpsbYvn0XCXSu3+WXU+Z/BOCJf0wu3Kl8nzm08XT+EIZwzbmx1/fgCVI//7O0oLNdLVLNEF39N7oJgLUeEIfhLh7y30YQP9/rMRy1qjIDNNi8x4/jXEukFCc9je5iwsQzy31qKTjo/7XVL0/gHE3g9FXGatid9YfBBJS1p4SzXbJ4DCxH0l7KY2s4z849hTSlTqTbpWAuPlhC7VK91CxcyO0mEX1F5nQZjtxJSPN1u1JflclU0KW2FnUzLY3pSp8VJ4aDhI+EzXBUfbE+WsVQ80lOUwfuJDZa4qrS0qAt+8UogAg7cfa0Zi+mnQ9G/Vlz5GhapuSQk=
