sudo: required
services:
- docker
language: node_js
node_js:
- '8'
script:
- npm test
after_success:
- sh .travis/push_dockerhub.sh
env:
  secure: 
    - OWa6u52wdZRddfl8ZZt3SFhv+fHS7tYdYZBg6W3I6/bXdYlJbl3RTpJkpso0uv5ZFxHdNkvu6dUZYv9F3xlQZdQaaVBtEULF9WH1TD+u8yQO6ycA/Id7HbhfRIiRV30ZRooga0Eavbow+kiiGY6QRsqf5I/jhorGijSxz0fHcyjJp2+RZL9b6p72Bd0Vk0TbVe1PPt7vLAzkBnEPpRYwuLl4CjCJ1lfTg2Czh6CLkGkBtkC1ltH1qxNZbCNIe1qHwN6nlnTQ558tDNbWZ3Imq9Pd96Ulkzo6Jsleeyz2r4qhS6cg6KKpjE8oLh/VIBgznt2hXrzMMtfrGqpmjpRt8mFEICp5z0FhA6bM0bgI7YMXwllY03a9LQUZV9vKRajUZwcng15sHbSc4W6YSYQlf3ql4rOkcI6S9HKopjtqBMIyBf4a5PC9+bnHpSZyhiQq7h49RvqRsu1IkjVIVRU3k80N9oV3rKb1JAoM/CiTX2md80XAMvPLa5t0GtwMWkyIS4yE5hXK1Wqhis80dOUd/fBaxCjl9b4mNhBO+micAvMY4/DNIOh9nQMd1RMZescsmxwJQNAIzcNLIgn/lu/XHeDp2zlNtVG3rul9fuDHlv13hWd+Hlk706Hi/AcTd63ySetu/cnV2cX09Qo0bORq5rAyPjfmtNBUvx/EQIRFW5g=
  global:
    - DOCKER_USER=iosr2017
