sudo: required
services:
- docker
language: node_js
node_js:
- '8'
script:
- npm test
after_success:
- sh .travis/push_dockerhub_registry.sh
- sh .travis/push_heroku_registry.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=clients
  - HEROKU_APP_NAME=caffessimo-clients
  - secure: E08OxEL5JL/VvJliAlBnJRtdin7GlZXqlRdiqX1rVoRFxxdYvh61a85z1BizXCB9PUwrr6A1+8L+8VVh35fOl+bXXmgs2dXxU7j4l7Yb6xm9aSkWvHnZ9ycyWvgJ7l9Hz9rX/jXCRsqdJjXiRtwsgwDRy+6W3u82FrbTyyRifMMCfzvef5QsW81q37thOBfDiNz8UJQVqHzT090U4EzyBL5PpoNr0pwnNrVeflvMHWtMoswWyFAVvWWRgreaGsWuXOMVtT0hAt9LhqyRu1mYpaUFTDDibAwH8TsmhknI/OY2M6nvU+Nr126zxZA7ikvW771wkhgOuHtY0kuSGEPGhgmIQXw/GhZO3sDfxjs8JNn0L6UMuqPuXlTLY+/LWtRPIkbM3oAb5/9xMrsmS41AHW/MNmcyL3BqX0SpH6OkjBCpS0so448NB5IKBzyMVEIuEJpHyZalRKXr3OYl9wvdXv6ZO8XUw+jXM0zPDdWlBPUtoaUorcHsNSbTixQmPPH3xhjA2zi+tsQCdYnIHqJus5ec7zlpvdP10B5dygxrT1asnTiTWsJJhsI7AYrSXmDL+Pyjd9d+MXXzZLOKyEyytx518kFr06vywGIkLe74ZMQOLbBLvYXjSvl1+ADmEvmZcxEIZLVuzOHhKc87bEJyUTvG91AqBeWGKVsGDDhR9ZM=
  - secure: GUrZnGXfT+EGaFlyoiuQJEq3piBLIoVXIqUXDf6yFJw/fdW4M0TXWsujOt9GiaWqiiP7716xZl1C1jdrYsGBZAL33NdLik/pqY5jnLL5iE5ZqHSg6xxM5d8Wmi0LRzdbRIG7KN6WEa2+WpcSBJDWozzE0+rn69Ffooh8fNXvAGPxphL1Im7NXAaOHMUPCSivL7/fRdn7M8KQDTx4VVGFc2/kI1Ih4Kvc2ODEATd79MKcKUPFBh7qlHKI2D1GNu1Ij6OwswAfb6lKqnztCfEofNzvBdMVckYQnCM3Aaqjm+CkPZJMb09PN6tChYvCstjCsXaMG/EeNlfnBmsdXzFduQty1iS9vIWu6VpsbYvn0XCXSu3+WXU+Z/BOCJf0wu3Kl8nzm08XT+EIZwzbmx1/fgCVI//7O0oLNdLVLNEF39N7oJgLUeEIfhLh7y30YQP9/rMRy1qjIDNNi8x4/jXEukFCc9je5iwsQzy31qKTjo/7XVL0/gHE3g9FXGatid9YfBBJS1p4SzXbJ4DCxH0l7KY2s4z849hTSlTqTbpWAuPlhC7VK91CxcyO0mEX1F5nQZjtxJSPN1u1JflclU0KW2FnUzLY3pSp8VJ4aDhI+EzXBUfbE+WsVQ80lOUwfuJDZa4qrS0qAt+8UogAg7cfa0Zi+mnQ9G/Vlz5GhapuSQk=
