sudo: required
services:
- docker
language: node_js
node_js:
- '8'
script:
- npm test
after_success:
- sh .travis/push_dockerhub_registry.sh
- sh .travis/push_heroku_registry.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=clients
  - HEROKU_APP_NAME=iosr2017-clients
  - secure: jg3Bw5m0tGsNQn8SdaZWu10lCL5G47iigKAJb/BDcAUO9DNdMwGIBGTjE7WeFMYQBokdtQyIB+iiOxbk+rGYwWq2ahcBlK26Bejp2pHFa8thkmo5ks+aS42fw5S9JSvIRjFcMQGA2Xbx3TZ9WRzi6SvazXML+levfgrsPnhxrPFqeqy86SvRDgl4ZOagf7+Kw6QNgABztRtDIxkgSwCDae1CnNfvZSL7J44Ms75TnGqVC/FKQfZVnvhM3ZLDHo2SCggcoP6y8lqYoaqfUDOetu/TxtY6y3frT+GtLTiUJxyD2LqJJmX/2Wb+t9toZH/C8byZ4RHFps7q1Eknz8aK4bJkHOqJLY9JLuAvjK+osRbJtwl7HlxTsiqQBzKZGCFrDMrM7RK7dJGhllGFiHm9do1t+48ctO6UAucebQgPCvpZtJnNX9xB0rDicAYVkw34aARRyXTOA86xuLreE96EtOHXIPfw3uc30znTzxodIQPKG01CYDZc9nQltgX79jRkf34FIyizc63Z+pKSfVYw9lvBvZMNzcHN1RFr4+NKD4f6nwtp7y/zJFlDLaZa6dCbQzmn1eGaMaOcYIoGeR6FivfVIWYOhIwYpwTslfNvutKaIPLZzIgDSjtfYfF2cIl04rvMzYXkCDFcPf5Ioy7m0r5ThupSpNrLsLnIrsR/BZE=
  - secure: GUrZnGXfT+EGaFlyoiuQJEq3piBLIoVXIqUXDf6yFJw/fdW4M0TXWsujOt9GiaWqiiP7716xZl1C1jdrYsGBZAL33NdLik/pqY5jnLL5iE5ZqHSg6xxM5d8Wmi0LRzdbRIG7KN6WEa2+WpcSBJDWozzE0+rn69Ffooh8fNXvAGPxphL1Im7NXAaOHMUPCSivL7/fRdn7M8KQDTx4VVGFc2/kI1Ih4Kvc2ODEATd79MKcKUPFBh7qlHKI2D1GNu1Ij6OwswAfb6lKqnztCfEofNzvBdMVckYQnCM3Aaqjm+CkPZJMb09PN6tChYvCstjCsXaMG/EeNlfnBmsdXzFduQty1iS9vIWu6VpsbYvn0XCXSu3+WXU+Z/BOCJf0wu3Kl8nzm08XT+EIZwzbmx1/fgCVI//7O0oLNdLVLNEF39N7oJgLUeEIfhLh7y30YQP9/rMRy1qjIDNNi8x4/jXEukFCc9je5iwsQzy31qKTjo/7XVL0/gHE3g9FXGatid9YfBBJS1p4SzXbJ4DCxH0l7KY2s4z849hTSlTqTbpWAuPlhC7VK91CxcyO0mEX1F5nQZjtxJSPN1u1JflclU0KW2FnUzLY3pSp8VJ4aDhI+EzXBUfbE+WsVQ80lOUwfuJDZa4qrS0qAt+8UogAg7cfa0Zi+mnQ9G/Vlz5GhapuSQk=
