version: "2"

services:
  clients:
    image: iosr2017/clients
    ports:
      - "5100:80"
  orders:
    image: iosr2017/orders
    ports:
      - "5101:80"
  storage:
    image: iosr2017/storage
    ports:
      - "5102:80"
  payments:
    image: iosr2017/payments
    ports:
      - "5103:80"
  menu:
    image: iosr2017/menu
    ports:
      - "5104:1433"