version: "2"
services:
  clients-service:
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - DB_NAME=iosr2017-clients
      - PORT=80
    build: ./../iosr-2017-clients
    image: iosr2017/clients
    ports:
      - "5100:80"
    links:
      - mongo
  orders-service:
    build: ./../iosr-2017-orders
    image: iosr2017/orders
    ports:
      - "5101:80"
    links:
      - mongo
      - menu-service
  payments-service:
    build: ./../iosr-2017-payments
    image: iosr2017/payments
    ports:
      - "5102:80"
    links:
      - mongo
  storage-service:
    build: ./../iosr-2017-storage
    image: iosr2017/storage
    ports:
      - "5103:80"
    links:
      - mongo
  menu-service:
    build: ./../iosr-2017-menu
    image: iosr2017/menu
    ports:
      - "5104:80"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes: 
      - /data/db